module Fake (
    Fake,
    runFaker,
    runFakerSeed,
    runFakerWith,
    integer,
    integerRange,
    natural,
    float,
    double,
    floatInRange,
    doubleInRange,
    bool,
    char,
    alpha,
    numeric,
    alphanumeric,
    string,
    stringBounded,
    elements,
    shuffle,
    vector,
    vectorOf,
    Fake.Combinators.sequence,
    maybeGen,
    oneof,
    filterGen,
    mapGen,
) where

import Fake.Combinators (
    filterGen,
    mapGen,
    maybeGen,
    oneof,
    vector,
    vectorOf,
 )
import qualified Fake.Combinators
import Fake.Core (Fake, runFaker, runFakerSeed, runFakerWith)
import Fake.Primitives (
    alpha,
    alphanumeric,
    bool,
    char,
    double,
    doubleInRange,
    elements,
    float,
    floatInRange,
    integer,
    integerRange,
    natural,
    numeric,
    shuffle,
    string,
    stringBounded,
 )
